namespace: citrix
name: adc

version: 1.2.0
readme: README.md
authors:
  - George Nikolopoulos <giorgos.nikolopoulos@citrix.com>
  - Sumanth Lingappa <sumanth.lingappa@citrix.com>

repository: https://github.com/citrix/citrix-adc-ansible-modules
issues: https://github.com/citrix/citrix-adc-ansible-modules/issues

description: Citrix ADC modules for Ansible
documentation: |
  https://github.com/citrix/citrix-adc-ansible-modules/tree/master/docs.
  Sample Playbooks to get you started can be found here - https://github.com/citrix/citrix-adc-ansible-modules/tree/master/samples.
license: MIT
tags:
  - networking
  - citrix
  - adc
