- option_name: throughput_avg
  type: float
  is_get_id: false
  is_delete_id: false
  description: 
    - Sum of throughput across all vips of the app.

- option_name: app_category
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Application Category.
    - Minimum length = 1
    - Maximum length = 255

- option_name: curclntconnections
  type: float
  is_get_id: false
  is_delete_id: false
  description: 
    - curclntconnections Value across all vips of the app.

- option_name: name
  type: str
  is_get_id: true
  is_delete_id: false
  description: 
    - Application Name.
    - Maximum length = 1024

- option_name: cursrvrconnections
  type: float
  is_get_id: false
  is_delete_id: false
  description: 
    - cursrvrconnections Value across all vips of the app.

- option_name: application_managed
  type: bool
  is_get_id: false
  is_delete_id: false
  description: 
    - Managed field.

- option_name: id
  type: str
  is_get_id: true
  is_delete_id: true
  description: 
    - Id is system generated key..

- option_name: family
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Application Family.
    - Minimum length = 1
    - Maximum length = 255

- option_name: app_criteria
  type: list
  is_get_id: false
  is_delete_id: false
  description: 
    - Application criteria.

- option_name: app_components
  type: list
  is_get_id: false
  is_delete_id: false
  description: 
    - Application components.

- option_name: no_of_auth
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of AUTH VIPs.

- option_name: no_of_gslb
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of GSLB VIPs.

- option_name: no_of_gslbsvc
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of LB VIPs.

- option_name: no_of_cr
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of CR VIPs.

- option_name: no_of_cs
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of CS VIPs.

- option_name: no_of_svc
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of Services.

- option_name: no_of_svcgrp
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of Service Groups.

- option_name: no_of_haproxy_be
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of Banckends.

- option_name: force_delete
  type: bool
  is_get_id: false
  is_delete_id: false
  description: 
    - force delete.

- option_name: no_of_svr
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of Servers.

- option_name: stylebook_params
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Stylebook Parameter.

- option_name: no_of_lb
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of LB VIPs.

- option_name: no_of_vpn
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of VPN VIPs.

- option_name: no_of_haproxy_fe
  type: str
  is_get_id: false
  is_delete_id: false
  description: 
    - Number of Frontends.

- option_name: application_ids
  type: list
  is_get_id: false
  is_delete_id: false
  description: 
    - Application IDs that are part of this application.
