
- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: server
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6

  tasks:
    - name: Get resource
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        expected_nitro_errorcode: [0, 258]
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: get

        resource: "{{ resource }}"
        name: "{{ attributes.name }}"
        attributes: "{{ attributes }}"


    - name: Add resource when not existing
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: add

        resource: "{{ resource }}"
        attributes: "{{ attributes }}"

      when: result.nitro_errorcode == 258

    - name: Update resource when existing
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: update

        resource: "{{ resource }}"
        name: "{{ attributes.name }}"
        attributes: "{{ attributes }}"

      when: result.nitro_errorcode == 0

