- hosts: netscaler
  gather_facts: no
  vars:
    resource: server
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6

  tasks:
    - name: Get resource
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: count

        resource: "{{ resource }}"
