- hosts: netscaler
  gather_facts: no

# nscli commands simulated
#
# delete simpleacl test-acl-rule1

  vars:
    resource: nssimpleacl
    attributes:
      aclname: test-acl-rule-1
      aclaction: DENY
      srcip: 10.102.29.5
      ttl: 600

  tasks:
    - name: delete resource
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: delete

        resource: "{{ resource }}"
        name: "{{ attributes.aclname }}"
