- hosts: netscaler
  gather_facts: no
  vars:
    resource: csvserver
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6

  tasks:
    - name: Get all cs vsevers
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: get_all

        resource: "{{ resource }}"

    - name: delete cs vservers
      delegate_to: localhost
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: delete

        resource: "{{ resource }}"
        name: "{{ item.name }}"
      with_items: "{{ result.nitro_object }}"
