- hosts: citrix_adc
  gather_facts: no

  tasks:
    - name: Get resource
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: action
        action: rename

        resource: server
        attributes:
          name: test-server-old
          newname: test-server-new
