- name: Add resource when not existing
  delegate_to: localhost
  citrix_adc_nitro_request:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"

    operation: add

    resource: "{{ resource }}"
    attributes: "{{ resource_attributes }}"
