- include_tasks: get_and_compare.yaml

- include_tasks: create_resource.yaml
  when: 
    - do_create
    - not dry_run

- include_tasks: update_resource.yaml
  when: 
    - do_update
    - not dry_run
