- hosts: netscaler
  gather_facts: no
  vars:
    resource: appfwlearningdata 

  tasks:
    - name: Get the unreviewed appfw learningdata for the specified profile and security check 
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: get_by_args

        resource: "{{ resource }}"
        args:
          profilename: testprofile 
          securitycheck: starturl 
