- hosts: netscaler

  vars:
    max_clients: 5

  gather_facts: False


  tasks:
    - name: setup appfw conf id field
      delegate_to: localhost
      register: result
      netscaler_appfw_confidfield:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        state: present

        fieldname: "field_name"
        url: "http://some.other.url"
        isregex: "REGEX"
        comment: Some comment
        disabled: no
