- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.citrixadc_modules


  tasks:
    - name: setup appfw json contenttype
      delegate_to: localhost
      register: result
      citrix_adc_appfw_xmlcontenttype:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: absent

        xmlcontenttypevalue: "xml.*regex"
        isregex: "REGEX"
