- hosts: netscaler

  vars:
    max_clients: 5

  gather_facts: False


  tasks:
    - name: setup appfw json contenttype
      delegate_to: localhost
      register: result
      netscaler_appfw_xmlcontenttype:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        state: absent

        xmlcontenttypevalue: "xml.*regex"
        isregex: "REGEX"
