- hosts: netscaler

  vars:
    max_clients: 5

  gather_facts: False


  tasks:
    - name: setup appfw signatures 
      delegate_to: localhost
      register: result
      netscaler_appfw_signatures:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        state: present 

        name: "from_yaml"
        src: "local://sample_sign.xml"
        comment: Some comment
        overwrite: yes 
