- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False

  tasks:
    - name: Setup mpsuser
      delegate_to: localhost
      citrix_adm_mpsuser:
        mas_ip: "{{ mas_ip }}"
        mas_user: "{{ mas_user }}"
        mas_pass: "{{ mas_pass }}"

        state: absent

        name: playbook_test_mpsuser_2
        password: 1234567

        session_timeout: 10
        session_timeout_unit: Minutes
        external_authentication: false
        enable_session_timeout: true
        groups: 
          - playbook_test_mpsgroup_2
