- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Login to mas
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        validate_certs: no
        adm_ip: "{{ adm_ip }}"
        adm_user: "{{ adm_user }}"
        adm_pass: "{{ adm_pass }}"

    - name: Setup mpsuser
      delegate_to: localhost
      citrix_adm_mpsuser:
        adm_ip: "{{ adm_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"
        validate_certs: no

        state: absent

        name: playbook_test_mpsuser_2
        password: 1234567

        session_timeout: 10
        session_timeout_unit: Minutes
        external_authentication: false
        enable_session_timeout: true
