- hosts: netscaler
  gather_facts: false

  tasks:

  - name: Setup cs action
    delegate_to: localhost
    register: result
    netscaler_cs_action:
      nitro_user: "{{nitro_user}}"
      nitro_pass: "{{nitro_pass}}"
      nsip: "{{nsip}}"

      name: action-2
      targetvserverexpr: '"mylb_" + HTTP.REQ.URL.SUFFIX'
