- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Setup ADNS service
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        module: netscaler_service
        state: present

        name: service-adns-1
        servicetype: ADNS
        ipaddress: 10.78.0.1
        port: 80

    - name: Setup gslb site 1
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        module: netscaler_gslb_site
        state: present

        sitename: gslb-site-basic
        siteipaddress: 10.78.50.1
        sitetype: LOCAL
        publicip: 10.1.1.1
        metricexchange: ENABLED

    - name: Setup gslb site 2
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        module: netscaler_gslb_site
        state: present

        sitename: gslb-site-2
        siteipaddress: 192.168.1.2
        sitetype: REMOTE
        triggermonitor: ALWAYS
