- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:

    - name: Setup gslb service
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        module: netscaler_gslb_service
        state: present

        servicename: gslb-service-1
        servicetype: HTTP
        port: 80
        sitename: gslb-site-1
        ipaddress: 192.168.3.5
        healthmonitor: "YES"
