- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Setup gslb site
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        ssl_cert_validation: "{{ ssl_cert_validation }}"

        module: netscaler_gslb_site
        operation: present

        sitename: gslb-site-1
        siteipaddress: 192.168.1.1
