# add server lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site 172.20.13.55
# add server lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site 172.20.15.55
# add gslb service lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site SSL 443 -publicIP 172.20.13.55 -publicPort 443 -siteName atl-qaern-silo1-site
# add gslb service lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site SSL 443 -publicIP 172.20.15.55 -publicPort 443 -siteName atl-qaern-silo2-site
# add gslb vserver jason_n.devgslb.homedepot.com SSL -lbMethod ROUNDROBIN -backupLBMethod LEASTCONNECTION
# bind gslb vserver jason_n.devgslb.homedepot.com -serviceName lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site
# bind gslb vserver jason_n.devgslb.homedepot.com -serviceName lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site
# bind gslb vserver jason_n.devgslb.homedepot.com -domainName jason_n.devgslb.homedepot.com -TTL 20
#
# This playbook replicates the functionality of the preceding nscli commands
#
# The values for nsip, nitro_user, and nitro_pass could be defined
# in the inventory file or anywhere else ansible permits variables to be defined.
#
# Alternatively they can take values from the environment variables
# NETSCALER_NSIP, NETSCALER_NITRO_USER, NETSCALER_NITRO_PASS and be omitted
# from the playbook entirely.
#
# The nscli commands do not iclude the configuration of the gslb sites
# atl-qaern-silo1-site, atl-qaern-silo2-site.
#
# Consequently we define these sites with arbitrary parameters
# preserving only their name as shown in the nscli commands


- hosts: netscaler

  gather_facts: False

  tasks:

    - name: Setup server 1
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        name: lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site
        ipaddress: 172.20.13.55

    - name: Setup server 2
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        name: lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site
        ipaddress: 172.20.15.55

    - name: Setup gslb site local
      delegate_to: localhost
      netscaler_gslb_site:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        sitename: atl-qaern-silo1-site
        sitetype: LOCAL
        siteipaddress: 172.20.13.1

    - name: Setup gslb site remote
      delegate_to: localhost
      netscaler_gslb_site:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        sitename: atl-qaern-silo2-site
        sitetype: REMOTE
        siteipaddress: 172.20.15.1

    - name: Setup gslb service 1
      delegate_to: localhost
      netscaler_gslb_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        servicename: lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site
        servername: lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site
        servicetype: SSL
        port: 443
        publicip: 172.20.13.55
        publicport: 443
        sitename: atl-qaern-silo1-site

    - name: Setup gslb service 2
      delegate_to: localhost
      netscaler_gslb_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        servicename: lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site
        servername: lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site
        servicetype: SSL
        port: 443
        publicip: 172.20.15.55
        publicport: 443
        sitename: atl-qaern-silo2-site

    - name: Setup gslb vserver
      delegate_to: localhost
      netscaler_gslb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        operation: present
        name: jason_n.devgslb.homedepot.com
        servicetype: SSL
        lbmethod: ROUNDROBIN
        backuplbmethod: LEASTCONNECTION

        service_bindings:
          - servicename: lb-vs-QA-443-v1-jason_n-atl-qaern-silo1-site
          - servicename: lb-vs-QA-443-v1-jason_n-atl-qaern-silo2-site

        domain_bindings:
          -
            domainname: jason_n.devgslb.homedepot.com
            ttl: 20
