- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Setup gslb site
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        module: netscaler_gslb_site
        state: present

        sitename: gslb-site-test-2
        siteipaddress: 192.168.1.1
