- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:

    - name: Setup gslb service
      delegate_to: localhost
      netscaler_gslb_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        servicename: gslb-service-test
        servicetype: HTTP
        port: 80
        sitename: gslb-site-test
        ipaddress: 192.168.3.5
        healthmonitor: yes
