---

- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:

    - name: Set service 1
      delegate_to: localhost
      netscaler_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: service-http-1
        servicetype: HTTP
        ipaddress: 10.78.0.1
        port: 80

    - name: Set lb monitor
      delegate_to: localhost
      netscaler_lb_monitor:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        monitorname: monitor_1
        type: HTTP-INLINE
        action: DOWN
        respcode: ['400']

    - name: Set service group
      delegate_to: localhost
      netscaler_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        servicemembers:
            - ip: 10.78.78.78
              port: 80
              weight: 60
            - ip: 10.79.79.79
              port: 80
              weight: 40
        monitorbindings:
          - monitorname: monitor_1
            weight: 100
