---

- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Set server 1
      local_action:
        module: netscaler_server
        nsip: 172.18.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: absent

        name: http-server-1
        ipaddress: 10.78.78.78

    - name: Set service 1
      local_action:
        module: netscaler_service
        nsip: 172.18.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: absent

        name: http-service-1
        servername: http-server-1
        servicetype: HTTP
        port: 80

    - name: Set server 2
      local_action:
        module: netscaler_server
        nsip: 172.18.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: absent

        name: http-server-2
        ipaddress: 10.79.79.79

    - name: Set service 2
      local_action:
        module: netscaler_service
        nsip: 172.18.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: absent

        name: http-service-2
        servername: http-server-2
        servicetype: HTTP
        port: 80


    - name: Set service group
      local_action:
        module: netscaler_servicegroup
        nsip: 172.18.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        servicemembers:
            - ip: 10.78.78.78
              port: 80
              weight: 60
            - ip: 10.79.79.79
              port: 80
              weight: 40

