---

- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Setup services
      local_action:
        module: netscaler_service_binding
        nsip: 172.17.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        ssl_cert_validation: no
        state: enabled

        weight: 100
        name: lb_vserver_1
        servicename: service_1

    - name: lb vserver test
      local_action:
        module: netscaler_service_group
        nsip: 172.17.0.2
        nitro_user: nsroot
        nitro_pass: nsroot
        ssl_cert_validation: no
        state: enabled

        weight: 100
        name: lb_vserver_1
        servicename: service-1
        servicegroupname: service_group_1
