---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:

    - name: Set service 1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: server_2
        ipaddress: 10.80.0.1
