---

- hosts: citrix_adc

  gather_facts: False

  tasks:

    - name: Password reset
      delegate_to: localhost
      citrix_adc_password_reset:
        nsip: "{{ nsip }}"
        username: "{{ nitro_user }}"
        nitro_protocol: https
        validate_certs: no
        password: "{{ password }}"
        new_password: "{{ new_password }}"
