---
- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Set server 1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present
        name: server-1
        ipaddress: 10.11.11.12

    - name: Set server 2
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present
        name: server-2
        ipaddress: 10.11.11.13

    - name: Set service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        clttimeout: 300
        autoscale: API
        servicemembers:
          mode: exact
          attributes:
            - servername: server-1
              port: 8080
              weight: 60

        monitor_bindings:
          mode: exact
          attributes:
            - monitor_name: myhttp3
              weight: 50
            - monitor_name: myhttp2
              weight: 50
