- hosts: netscaler

  vars:
    max_clients: 5
  gather_facts: False

  tasks:
    - name: Setup server
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        state: present


        name: test-server-1
        ipaddress: 192.168.2.2
        disabled: no
