---
- hosts: netscaler

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Set server 1
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present
        name: server-1
        ipaddress: 192.168.1.1

    - name: Set server 2
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present
        name: server-2
        ipaddress: 192.168.1.2

    - name: Set service group
      delegate_to: localhost
      netscaler_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        servicemembers:
            - servername: server-1
              port: 80
              weight: 60
            - servername: server-2
              port: 80
              weight: 40
