- name: Get resource
  delegate_to: localhost
  register: result
  citrix_adc_nitro_request:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"

    operation: delete

    resource: "{{ resource }}"
    name: "{{ resource_name }}"
