- name: Get entity
  delegate_to: localhost
  citrix_adc_nitro_request:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"

    operation: get
    
    expected_nitro_errorcode: "{{ get_acceptable_error_codes }}"

    resource: "{{ resource }}"
    name: "{{ resource_name }}"
  register: get_result



- name: Set get entity output variables
  set_fact:
    resource_exists: "{{ get_result.nitro_errorcode == 0 }}"
    do_create: false
    do_update: false



- name: Set output variables default values
  set_fact:
    "{{ debug_prefix }}nitro_object": none
    "{{ debug_prefix }}resource_deleted": "{{ resource_exists }}"

- name: Set output variables
  set_fact:
    "{{ debug_prefix }}nitro_object": "{{ get_result.nitro_object[0] }}"
  when: resource_exists
