- hosts: citrix_adc
  remote_user: nsroot
  connection: ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python

    # Any valid nscli command works
    nscli_command: "show ns ip"


  tasks:
    - name: Run nscli command
      shell: nscli -s -U :nsroot:nsroot "{{ nscli_command }}"
      register: nscli_output

    - name: Show nscli output
      debug:
          msg: "{{ nscli_output }}"
