#
# Execute like: ansible-playbook show_tech_support.yml -i hosts
#
- hosts: citrix_adc
  remote_user: nsroot
  connection: ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python


  tasks:
    - name: Generate technical support bundle
      shell: nscli -s -U :nsroot:nsroot "show techsupport"
      register: sts_output

    - name: Parse output to find tarball path
      set_fact:
        sts_bundle: "{{ (sts_output.stdout_lines | select('search', 'points to') | list | first ).split('points to --->')[1] | trim }}"

    - name: Download STS Bundle locally
      fetch:
        src: "{{ sts_bundle }}"
        dest: "my_ns_sts"

    - debug:
        msg: "STS Bundle downloaded locally into the following directory: ./my_ns_sts{{ sts_bundle }}"
