- hosts: citrix_adc
  gather_facts: no


  tasks:
    - name: Create lb vserver dry run
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some comment'

    - name: Assert dry run creation
      assert:
        that:
          role_output.operation == 'create'

    - name: Create lb vserver for real
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some comment'

    - name: Assert actual creation
      assert:
        that:
          role_output.operation == 'create'

    - name: Create lb vserver identical dryrun
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some comment'

    - name: Assert actual creation
      assert:
        that:
          role_output.operation == 'none'

    - name: Create lb vserver identical actual
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some comment'

    - name: Assert actual creation
      assert:
        that:
          role_output.operation == 'none'

    - name: Update lb vserver dry run
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some other comment'

    - name: Assert update dry run
      assert:
        that:
          role_output.operation == 'update'

    - name: Update lb vserver actual
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some other comment'


    - name: Assert update actual
      assert:
        that:
          role_output.operation == 'update'

    - name: Get updated lb vserver
      import_role:
        name: adc_resource_get
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 80
            comment: 'some other comment'

    - name: Assert update actual
      assert:
        that:
          role_output.nitro_object.comment == 'some other comment'

    - name: Update non updateable lb vserver dry run
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 8080
            comment: 'some other comment'

    - name: Assert non updateable dry run
      assert:
        that:
          - role_output.operation == 'recreate'
          - role_output.non_updateable_attributes_conflict

    - name: Update non updateable lb vserver actual
      import_role:
        name: adc_resource_create_or_update
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 8080
            comment: 'some other comment'

    - name: Assert non updateable actual
      assert:
        that:
          - role_output.operation == 'recreate'
          - role_output.non_updateable_attributes_conflict

    - name: Get updated entity
      import_role:
        name: adc_resource_get
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258
          non_updateable_attributes:
            - servicetype
            - port
            - range
            - state
            - td
            - redirurlflags
          resource_attributes:
            name: inte_test_lbvserver
            servicetype: HTTP
            ipv46: 12.21.33.33
            port: 8080
            comment: 'some other comment'

    - name: Assert non updateable actual
      assert:
        that:
          - role_output.nitro_object.port == 8080

######################
# Delete role checks #
######################

    - name: Delete resource dry run
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258

    - name: Assert deletion dry run
      assert:
        that:
          role_output.operation == 'delete'

    - name: Delete resource actual
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258

    - name: Assert deletion actual
      assert:
        that:
          role_output.operation == 'delete'

    - name: Delete non existent resource dry run
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          dry_run: true
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258

    - name: Assert non existent delete dry run
      assert:
        that:
          role_output.operation == 'none'

    - name: Delete non existent resource actual
      import_role:
        name: adc_resource_delete
      vars:
        role_input:
          resource: lbvserver
          resource_name: inte_test_lbvserver
          resource_missing_errorcode:
            - 258

    - name: Assert non existent delete actual
      assert:
        that:
          role_output.operation == 'none'
