namespace: citrix
name: adm

version: 1.0.0

readme: README.md

repository: https://github.com/citrix/citrix-adc-ansible-modules
issues: https://github.com/citrix/citrix-adc-ansible-modules/issues

authors:
- George Nikolopoulos <giorgos.nikolopoulos@citrix.com>


description: Citrix ADM modules

license: MIT License
tags:
  - networking
  - citrix
  - adm


